books/urls.py
from unicodedata import name
from django.urls import path
from .views import HomePage, GenreView, BookDetails, CreateBook, UpdateBook
from django.views.generic.base import TemplateView

app_name = 'bookstore'
urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('add-book/', CreateBook.as_view(), name='create-book'),
    path('edit/<slug:slug>/', UpdateBook.as_view(), name='update-book'),
    path('error/', TemplateView.as_view(template_name='error.html')),
    path('genre/<str:g>/', GenreView.as_view(), name='genre'),
    path('<slug:slug>/', BookDetails.as_view(), name='details'),
]

bookstore/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls', namespace='bookstore'))
]

books/models.py
import imp
from django.db import models
from django.template.defaultfilters import slugify

# Create your models here.
class Books(models.Model):
    # Example model only
    title = models.CharField(max_length=100)
    slug = models.SlugField(null=True)
    genre = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    isbn = models.CharField(max_length=100)
    count = models.IntegerField(null=True, default=0)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)            
        return super().save(*args, **kwargs)
    
    def __str__(self):
        return self.title
        

books/forms.py
from .models import Books
from django import forms

class BookAddForm(forms.ModelForm):
    class Meta:
        model = Books
        fields = ('title', 'genre', 'author', 'isbn', )

        widgets = {
            'title' : forms.TextInput(attrs={'class': 'form-control'}),
            'genre' : forms.TextInput(attrs={'class': 'form-control'}),
            'author' : forms.TextInput(attrs={'class': 'form-control'}),
            'isbn' : forms.TextInput(attrs={'class': 'form-control'}),
        }

books/views.py
from django.utils import timezone
from django.db.models import F
# from django.views.generic.base import TemplateView
from django.views.generic import ListView, DetailView
from django.views.generic.edit import  CreateView, UpdateView
from .models import Books
# from django.shortcuts import redirect, render
from django.contrib.auth.mixins import PermissionRequiredMixin
from .mixins import UserAccessMixin
from .forms import BookAddForm
# Create your views here.


class HomePage(ListView):
    model = Books
    template_name = 'index.html'
    context_object_name = 'books'

class GenreView(ListView):
    model = Books
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['books'] = Books.objects.filter(genre__icontains=self.kwargs['g'])

        return context


class BookDetails(DetailView):    
    template_name = 'book-detail.html'
    model = Books
    context_object_name = 'book'

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        post = Books.objects.get(slug=self.kwargs['slug'])
        post.count = F('count')+1
        post.save()
        context['time'] = timezone.now()
        return context


class CreateBook(UserAccessMixin, CreateView):
    permission_required = 'books.add_books'
    login_url = '/' # this is wrong. Yeah, but its just for testing purposes
    model = Books
    template_name = 'forms/book-create.html'
    form_class = BookAddForm
    success_url = '/'

class UpdateBook(UserAccessMixin, UpdateView):
    permission_required ='books.change_books'
    redirect_field_name ='next'
    raise_exception = False
    login_url = '/' # this is wrong. Yeah, but its just for testing purposes
    model = Books
    template_name = 'forms/book-create.html'
    form_class = BookAddForm
    success_url = '/'


# other methods for the same stuff above

"""
TemplateView in place of ListView

class HomePage(TemplateView):
    template_name = 'index.html'
    
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['books'] = Books.objects.all()
        return context


function based view in place of hompage list view

def homepage(request):
    books = Books.objects.all()
    context ={
        'books':books
    }

    return render(request, 'index.html', context)


function based view for the GenreView

def categorize(request, **kwargs):
    books = Books.objects.filter(genre__icontains=kwargs['g'])
    print(books)
    context = {
        'books' : books,
    } 

    return render(request, 'index.html', context)
    
function based view for Book Details


def bookDetails(request, slug):
    book = Books.objects.get(slug=slug)
    book.count +=1
    book.save()
    time = timezone.now()
    context = {
        'book':book,
        'time':time,
    }

    return render(request, 'book-detail.html', context)

form view

class CreateBook(FormView):
    template_name = 'forms/book-create.html'
    form_class = BookAddForm
    success_url = '/'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

create view

def createBook(request):
    form = BookAddForm()
    if request.method == 'POST':
        form = BookAddForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
        else:
            form = BookAddForm()
    context = {
        'form' : form,
    }

    return render(request, 'forms/book-create.html', context)




update view 

def updateBook(request, slug):
    book = Books.objects.get(slug=slug)
    form = BookAddForm(instance=book)

    if request.method == 'POST':
        form = BookAddForm(request.POST, instance=book)
        if form.is_valid():
            form.save()
            return redirect('/')
        else:
            form = BookAddForm()
    context = {
        'form':form,
    }
    return render(request, 'forms/book-create.html', context)




"""

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>{% block title %} Welcome to Books {% endblock %}</title>
</head>

<body>
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
</body>

</html>

templates/book-detail.html
    {% extends "base.html" %}
    {% block content %}
    <div class="container" style="max-width:800px">
        <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">{{book.title}}</h1>
            <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">Genre: {{book.genre}}</small>
                <small class="text-muted">ISBN: {{book.isbn}}</small>
                <small class="text-muted">views: {{book.count}}</small>
                <small class="text-muted">Time: {{time}}</small>
            </div>            
        </div>
        <a href="{% url 'bookstore:update-book' book.slug %}"><button class="btn btn-primary">Edit -- {{book.title}}</button></a>
    </div>
    {% endblock %}

templates/error.html
{% extends 'base.html' %}

{% block title %}Page not found{% endblock %}
{% block content %}
    <body>
        <div class="d-flex align-items-center justify-content-center vh-100">
            <div class="text-center">
                <h1 class="display-1 fw-bold">404</h1>
                <p class="fs-3"> <span class="text-danger">Opps!</span> Page not found.</p>
                <p class="lead">
                    The page you’re looking for doesn’t exist.
                  </p>
                <a href="{% url 'bookstore:home' %}" class="btn btn-primary">Go Home</a>
            </div>
        </div>
    </body>
{% endblock %}

templates/forms/book-create.html
{% extends "base.html" %}
{% block content %}
<div class="container" style="max-width:600px">
    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">All Books</h1>
        <p class="lead">A range of wonderful programming books to help you learn Programming.</p>
    </div>
    <div class="py-5">
        <div class="row">
            <div class="col-12">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Save Book</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/index.html
    {% extends "base.html" %}
    {% block content %}
    <div class="container">
        <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">All Books</h1>
            <p class="lead">A range of wonderful programming books to help you learn Programming in 2023.</p>
        </div>
        <div class="py-5">
            <div class="row">
                {% for book in books %}
                <div class="col-md-4">
                    <a class="text-dark" href="">
                        <div class="card mb-4 box-shadow">
                            <div class="card-body">
                                <a href="{% url 'bookstore:details' book.slug %}"><h2 style="font-size:18px;font-weight:bold;min-height:42px;">{{book.title|truncatechars:50}}</h2></a>
                                <div class="d-flex justify-content-between align-items-center">
                                    <a href="{% url 'bookstore:genre' book.genre %}"><small class="text-muted">{{book.genre}}</small></a>
                                    <small class="text-muted">{{book.isbn}}</small>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}                
            </div>
            <div class="px-12">
                <a href="{% url 'bookstore:create-book' %}"><button class="btn btn-primary">Add new book</button></a>                
            </div>

        </div>
    </div>
    {% endblock %}